[phases.setup]
nixpkgs = ["php", "composer", "nodejs", "yarn"]

[phases.build]
cmds = [
  "composer install",
  "yarn install",
  "yarn build",
  "php artisan migrate --force",
  "php artisan optimize",
  "chmod -R 777 storage/",
  "chmod -R 777 bootstrap/cache",
  "php artisan storage:link"
]
